import './globals.css'
import { sarabun } from './fonts'
import localFont from 'next/font/local'
import { Providers } from "./providers";
import Nav from '../components/nav'
import Footer from '../components/footer'

// const sarabun = Sarabun({ subsets: ['thai', 'latin'], weight: '400', })

export const metadata = {
  title: 'Gen ED',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sarabun.className}>
 	      <Providers>
          <Nav/>
          {children}
          <Footer/>
      	</Providers>
      </body>
    </html>
    
  )
}

 